## Template for class generated by Claude Sonnet 4.5 ##

class SpinKpointArray:
    """
    A wrapper around a 2D NumPy array that provides additional indexing
    for spin and k-point dimensions using Pythonic bracket notation.
    
    The internal array has shape (n_spin, n_kpoints, *base_shape) where
    base_shape is the shape of the underlying 2D array.
    
    Indexing works with a tuple: arr[spin, kpoint, i, j]
    - Use None or : to get all elements in a dimension
    - Use integers to select specific indices
    
    Parameters
    ----------
    base_array : tuple indexed array of np.ndarry/NPScal arrays
        The spin/k-point indexed quantity to wrap
    n_spin : int
        Number of spin components (default: 2 for spin-up/spin-down)
    n_kpoints : int
        Number of k-points (default: 1)
    dtype : np.dtype, optional
        Data type for the array. If None, uses base_array's dtype
    
    Examples
    --------
    >>> arr = SpinKpointArray.zeros((3, 4), n_spin=2, n_kpoints=5)
    >>> arr[0, 2]           # Get 2D array for spin=0, kpoint=2
    >>> arr[0, 2, 1, 3]     # Get single element
    >>> arr[0, :, :, :]     # Get all data for spin=0
    >>> arr[0, 2] = 1.0     # Set entire 2D slice
    >>> arr[1, 3, 2, 1] = 5 # Set single element
    """
    
    def __init__(
        self,
        base_array_dict,
        n_spin: int = 1,
        n_kpoints: int = 1,
    ):
        """Initialize the SpinKpointArray wrapper."""
        if base_array_dict[(0,0)].ndim != 2:
            raise ValueError(f"base_array must be 2D, got shape {base_array.shape}")
        
        if n_spin < 1:
            raise ValueError(f"n_spin must be >= 1, got {n_spin}")
        
        if n_kpoints < 1:
            raise ValueError(f"n_kpoints must be >= 1, got {n_kpoints}")
        
        self.n_spin = n_spin
        self.n_kpoints = n_kpoints
        self.base_shape = base_array_dict[(0,0)].shape

        # Create the 2D Dictionary with array: (n_spin, n_kpoints, dim0, dim1)
        #dtype = dtype or base_array.dtype
        self.data = base_array_dict

        # We don't actually do any transpose operations here - the transpose tag is
        # passed to the relevant scalapack function
        self.transpose = [False]
    
    #@classmethod
    #def zeros(
    #    cls,
    #    base_shape: Tuple[int, int],
    #    n_spin: int = 2,
    #    n_kpoints: int = 1,
    #    dtype: np.dtype = np.float64
    #) -> 'SpinKpointArray':
    #    """Create a SpinKpointArray initialized with zeros."""
    #    base_array = np.zeros(base_shape, dtype=dtype)
    #    return cls(base_array, n_spin, n_kpoints, dtype)
    
    #@classmethod
    #def ones(
    #    cls,
    #    base_shape: Tuple[int, int],
    #    n_spin: int = 2,
    #    n_kpoints: int = 1,
    #    dtype: np.dtype = np.float64
    #) -> 'SpinKpointArray':
    #    """Create a SpinKpointArray initialized with ones."""
    #    base_array = np.ones(base_shape, dtype=dtype)
    #    return cls(base_array, n_spin, n_kpoints, dtype)
    
    def __getitem__(self, key):
        """
        Get data using bracket notation: arr[spin, kpoint, i, j]
        
        Parameters
        ----------
        key : int, slice, tuple, or Ellipsis
            Index specification. Can be:
            - Single int: arr[0] returns all data for spin=0
            - Tuple: arr[0, 2] or arr[0, 2, 1, 3]
            - Slices: arr[0, :, :, :] or arr[:, 0]
            - Ellipsis: arr[0, ..., 3] expands to arr[0, :, :, 3]
        
        Returns
        -------
        np.ndarray
            Sliced array based on the provided indices
        
        Examples
        --------
        >>> arr[0, 2]           # Get 2D array for spin=0, kpoint=2
        >>> arr[0, 2, 1, 3]     # Get single element
        >>> arr[0]              # Get 3D array for spin=0 (all kpoints)
        >>> arr[:, 0]           # Get 3D array for kpoint=0 (all spins)
        >>> arr[0, :, 1]        # Get 2D array (all kpoints, row 1)
        """
        # Convert key to tuple if it isn't already
        if not isinstance(key, tuple):
            key = (key,)
        
        # Handle ellipsis by expanding it
        if Ellipsis in key:
            # Count how many dimensions are specified
            n_specified = len([k for k in key if k is not Ellipsis])
            n_missing = 4 - n_specified
            
            # Replace ... with the right number of colons
            expanded_key = []
            for k in key:
                if k is Ellipsis:
                    expanded_key.extend([slice(None)] * n_missing)
                else:
                    expanded_key.append(k)
            key = tuple(expanded_key)
        
        # Pad with slices if needed (e.g., arr[0] -> arr[0, :, :, :])
        if len(key) < 4:
            key = key + (slice(None),) * (4 - len(key))

        if isinstance(key[0], int):
            spin_slice_min = key[0]
            spin_slice_max = key[0] + 1
        else:
            raise Exception("Slice indexing for spins currently not supported")
        if isinstance(key[1], int):
            kpt_slice_min = key[1]
            kpt_slice_max = key[1] + 1
        else:
            raise Exception("Slice indexing for k-points currently not supported")            

        if isinstance(key[0], slice):
            if key[0].start is None:
                spin_slice_min = 0
            else:
                spin_slice_min = key[0].start
            if key[0].stop is None:
                spin_slice_max = self.n_spin
            else:
                spin_slice_max = key[0].stop

        if isinstance(key[1], slice):
            if key[1].start is None:
                kpt_slice_min = 0
            else:
                kpt_slice_min = key[1].start
            if key[1].stop is None:
                kpt_slice_max = self.n_kpoints
            else:
                kpt_slice_max = key[1].stop

        for isp in range(spin_slice_min, spin_slice_max):
            for ikpt in range(kpt_slice_min, kpt_slice_max):
                if slice_all_check(key[2]) and slice_all_check(key[3]):
                    return self.data[(isp, ikpt)]
                else:
                    return self.data[(isp, ikpt)][key[2],key[3]]

    def __setitem__(self, key, value):
        """
        Set data using bracket notation: arr[spin, kpoint, i, j] = value
        
        Parameters
        ----------
        key : int, slice, tuple, or Ellipsis
            Index specification (same format as __getitem__)
        value : np.ndarray or scalar
            Value(s) to set. Must be broadcastable to the selected slice
        
        Examples
        --------
        >>> arr[0, 2] = 1.0              # Set entire 2D slice
        >>> arr[1, 3, 2, 1] = 5.0        # Set single element
        >>> arr[0] = np.ones((5, 3, 4))  # Set all kpoints for spin=0
        >>> arr[:, 0] = 2.0              # Set all spins for kpoint=0
        """        
        # Convert key to tuple if it isn't already
        if not isinstance(key, tuple):
            key = (key,)

        # Handle ellipsis
        if Ellipsis in key:
            n_specified = len([k for k in key if k is not Ellipsis])
            n_missing = 4 - n_specified

            expanded_key = []
            for k in key:
                if k is Ellipsis:
                    expanded_key.extend([slice(None)] * n_missing)
                else:
                    expanded_key.append(k)
            key = tuple(expanded_key)

        # Pad with slices if needed
        if len(key) < 4:
            key = key + (slice(None),) * (4 - len(key))

        if isinstance(key[0], int):
            spin_slice_min = key[0]
            spin_slice_max = key[0] + 1
        if isinstance(key[1], int):
            kpt_slice_min = key[0]
            kpt_slice_max = key[0] + 1

        if isinstance(key[0], slice):
            if key[0].start is None:
                spin_slice_min = 0
            else:
                spin_slice_min = key[0].start
            if key[0].stop is None:
                spin_slice_max = self.n_spin
            else:
                spin_slice_max = key[0].stop

        if isinstance(key[1], slice):
            if key[1].start is None:
                kpt_slice_min = 0
            else:
                kpt_slice_min = key[1].start
            if key[1].stop is None:
                kpt_slice_max = self.n_kpoints
            else:
                kpt_slice_max = key[1].stop

        if isinstance(value, self.__class__):
            for isp in range(spin_slice_min, spin_slice_max):
                for ikpt in range(kpt_slice_min, kpt_slice_max):
                    if slice_all_check(key[2]) and slice_all_check(key[3]):
                        self.data[(isp, ikpt)] = value[(isp, ikpt)]
                    else:
                        self.data[(isp, ikpt)][key[2],key[3]] = value[(isp, ikpt)][key[2],key[3]]
        else:
            for isp in range(spin_slice_min, spin_slice_max):
                for ikpt in range(kpt_slice_min, kpt_slice_max):
                    if slice_all_check(key[2]) and slice_all_check(key[3]):
                        self.data[(isp, ikpt)] = value
                    else:
                        self.data[(isp, ikpt)][key[2],key[3]] = value

    def __repr__(self) -> str:
        """String representation of the SpinKpointArray."""
        return (f"SpinKpointArray(n_spin={self.n_spin}, "
                f"n_kpoints={self.n_kpoints}, "
                f"base_shape={self.base_shape},)")
    
    def __str__(self) -> str:
        """User-friendly string representation."""
        return self.__repr__()
    
    #@property
    #def shape(self) -> Tuple[int, ...]:
    #    """Full shape of the underlying data array."""
    #    return self.data.shape

    #@property
    #def dtype(self) -> np.dtype:
    #    """Data type of the array."""
    #    return self.data.dtype

    def copy(self) -> 'SpinKpointArray':
        """Create a deep copy of the SpinKpointArray."""
        new_instance = SpinKpointArray.__new__(SpinKpointArray)
        new_instance.n_spin = self.n_spin
        new_instance.n_kpoints = self.n_kpoints
        new_instance.base_shape = self.base_shape
        new_instance.data = self.data.copy()
        return new_instance
    
    # Add NumPy-like array protocol methods for better integration
    #def __array__(self) -> np.ndarray:
    #    """Return the underlying NumPy array when using np.array() or np.asarray()."""
    #    return self.data

    def __len__(self):
        """Return the length of the array by the number of spins and number of k-points."""
        return self.n_spin * self.n_kpoints

    def __iter__(self):
        """Iterate over spin dimension."""
        for spin in range(self.n_spin):
            for kpt in range(self.n_kpoints):
                print(spin, kpt)
                yield self[spin, kpt]

    def __add__(self, val):
        new_data = self.copy()
        for spin in range(self.n_spin):
            for kpt in range(self.n_kpoints):
                new_data[spin, kpt] = self[spin, kpt] + val[spin, kpt]
        return new_data

    def __sub__(self, val):
        new_data = self.copy()
        for spin in range(self.n_spin):
            for kpt in range(self.n_kpoints):
                new_data[spin, kpt] = self[spin, kpt] - val[spin, kpt]
        return new_data

    def __matmul__(self, val):
        new_data = self.copy()
        for spin in range(self.n_spin):
            for kpt in range(self.n_kpoints):
                if (self.transpose[0]) and (not val.transpose[0]):
                    new_data[spin, kpt] = self[spin, kpt].T @ val[spin, kpt]
                if (not self.transpose[0]) and (val.transpose[0]):
                    new_data[spin, kpt] = self[spin, kpt] @ val[spin, kpt].T
                if (self.transpose[0]) and (val.transpose[0]):
                    new_data[spin, kpt] = self[spin, kpt].T @ val[spin, kpt].T
                if (not self.transpose[0]) and (not val.transpose[0]):
                    new_data[spin, kpt] = self[spin, kpt] @ val[spin, kpt]

        new_data = new_data.N
        self = self.N
        val = val.N
                    
        return new_data

    def __mul__(self, val):
        new_data = self.copy()
        for spin in range(self.n_spin):
            for kpt in range(self.n_kpoints):
                new_data[spin, kpt] = self[spin, kpt] * val
        return new_data

    def __div__(self, val):
        new_data = self.copy()
        for spin in range(self.n_spin):
            for kpt in range(self.n_kpoints):
                new_data[spin, kpt] = self[spin, kpt] / val
        return new_data

    @property
    def T(self):
        self.transpose = [True]
        return self

    @property
    def N(self):
        self.transpose = [False]
        return self


def slice_all_check(slicefunc):
    if (slicefunc.start is None) and (slicefunc.start is None):
        return True
    else:
        return False


if __name__ == "__main__":
    import numpy as np

    dm1 = np.array([[1,2],[1,2]])
    dm2 = np.array([[2,2],[1,2]])
    dm3 = np.array([[3,2],[1,2]])
    dm4 = np.array([[4,2],[1,2]])
    dm_dict = {(0,0): dm1,
               (1,0): dm2,
               (0,1): dm3,
               (1,1): dm4}
    
    array = SpinKpointArray(dm_dict, 2, 2)

    new_array = array @ array.T

    for i in new_array:
        print(i)
    
